Algoritmo "CemaZeroPara"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : LC
// Descrição   : O programa conta de cem a zero usando Para
// Autor(a)    : Victor Schernikau Bahia Bittencourt Vieira
// Data atual  : 13/03/2024
Var
// Seção de Declarações das variáveis
valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para valor de 0 ate 100 passo 1 faca
escreval(valor)
fimpara
Fimalgoritmo