Algoritmo "EternoPatoXiter"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : LC
// Descrição   : O programa pergunta qual animal faz quack até a pessoa acertar
// Autor(a)    : Victor Schernikau Bahia Bittencourt Vieira
// Data atual  : 12/03/2024
Var
// Seção de Declarações das variáveis 
animal: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Qual animal que faz Quack Quack?")
leia(animal)
se(animal="pato")entao
escreval("Isso mesmo! O animal é o Pato!")
senao
se(animal="Pato")entao
escreval("Isso mesmo! O animal é o Pato!")
senao
se(animal="nathan")entao
escreval("Eterno Pato Xiter. Caráter=0")
senao
se(animal="Nathan")entao
escreval("Eterno Pato Xiter. Caráter=0")
senao
se(animal="sinai")entao
escreval("Eterno Pato Xiter. Caráter=0")
senao
se(animal="Sinai")entao
escreval("Eterno Pato Xiter. Caráter=0")
fimse
fimse
fimse
fimse
fimse
fimse
enquanto (animal<>"pato") e (animal<>"Pato") e (animal <>"nathan") e (animal<>"Nathan") e (animal<>"sinai") e (animal<>"Sinai")faca
escreval("Qual animal que faz Quack Quack?")
leia(animal)
se(animal="pato") ou (animal="Pato")entao
escreval("Isso mesmo! O animal é o Pato!")
senao
se(animal="nathan")entao
escreval("Eterno Pato Xiter. Caráter=0")
senao
se(animal="Nathan")entao
escreval("Eterno Pato Xiter. Caráter=0")
senao
se(animal="sinai")entao
escreval("Eterno Pato Xiter. Caráter=0")
senao
se(animal="Sinai")entao
escreval("Eterno Pato Xiter. Caráter=0")
fimse
fimse
fimse
fimse
fimse
fimenquanto
Fimalgoritmo