Algoritmo "RepetiçaoZeroCem"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : LC
// Descrição   : O programa printa uma lista de 0 até 100 com o comando repita
// Autor(a)    : Victor Schernikau Bahia Bittencourt Vieira
// Data atual  : 12/03/2024
Var
// Seção de Declarações das variáveis 
valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
valor:=0
repita
escreva(valor)
valor:=valor+1
ate valor>100

Fimalgoritmo