Algoritmo "ContagemCemZero"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : LC
// Descrição   : O Programa conta de Cem a Zero
// Autor(a)    : Victor Schernikau Bahia Bittencourt Vieira
// Data atual  : 12/03/2024
Var
// Seção de Declarações das variáveis 
valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
valor:=100
escreval(valor)
enquanto (valor<>0)faca
valor:=valor-1
escreval(valor)
fimenquanto
Fimalgoritmo