Algoritmo "DezaCinquentaPara"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : LC
// Descrição   : O programa faz uma lista de 10 até 50 com comando PARA
// Autor(a)    : Victor Schernikau Bahia Bittencourt Vieira
// Data atual  : 13/03/2024
Var
// Seção de Declarações das variáveis
valor: inteiro

// Seção de Comandos, procedimento, funções, operadores, etc...
inicio
para valor de 10 ate 50 faca
escreva (valor:5)
fimpara
Fimalgoritmo