Algoritmo "DezaCemParaVertical"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : LC
// Descrição   : O programa faz uma lista de 10 até 100 com comando PARA
// Autor(a)    : Victor Schernikau Bahia Bittencourt Vieira
// Data atual  : 13/03/2024
Var
// Seção de Declarações das variáveis
valor: inteiro

// Seção de Comandos, procedimento, funções, operadores, etc...
inicio
para valor de 10 ate 100 faca
escreval (valor:1)
fimpara
Fimalgoritmo