Algoritmo "RepetiçaoDezCinquenta"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : LC
// Descrição   : O programa printa uma lista de 10 até 50 com o comando repita
// Autor(a)    : Victor Schernikau Bahia Bittencourt Vieira
// Data atual  : 12/03/2024
Var
// Seção de Declarações das variáveis 
 valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
valor:=10
repita
escreva(valor)
valor:=valor+1
ate valor>50

Fimalgoritmo